### ISSUE TITLE
modify front-end user design and various files

### ISSUE THREAD

**Issue by alyssa-greenwell** [manoamarketplace/manoamarketplace#50]

**Comment by alyssa-greenwell** [comment]
add style for buttons and links

**Comment by jazminlor** [comment]
modify "more-info" page (fix images + sizing), "profile" page (fix/make the item cards the same size or similar & reload page when user goes from "List Users" -> "Profile" -> their own profile. currently does not reload to their own profile.), & other fixes along the way

**Comment by jingtzheng** [comment]
make the title of the pages uniform (like the categories title is green and the others are black so make it uniformed)

**Comment by jazminlor** [comment]
edit sign-up page and "Create Profile" page to auto-fill first name, last name, and email. also change "Add Item" to "Add Listing".
